"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 4.2.7.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

import os
import sys
from datetime import timedelta
from pathlib import Path

import dj_database_url
from decouple import Csv, config

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Core settings

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = config("SECRET_KEY", default="django-insecure-dev-key-change-in-production")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = config("DEBUG", default=True, cast=bool)

ALLOWED_HOSTS = config(
    "ALLOWED_HOSTS",
    default="localhost,127.0.0.1",
    cast=lambda v: [s.strip() for s in v.split(",")],
)

INTERNAL_ALLOWED_HOSTS = config("INTERNAL_ALLOWED_HOSTS", default="", cast=Csv())
for internal_host in INTERNAL_ALLOWED_HOSTS:
    if internal_host and internal_host not in ALLOWED_HOSTS:
        ALLOWED_HOSTS.append(internal_host)

# Render.com specific
RENDER_EXTERNAL_HOSTNAME = os.environ.get("RENDER_EXTERNAL_HOSTNAME")
if RENDER_EXTERNAL_HOSTNAME:
    ALLOWED_HOSTS.append(RENDER_EXTERNAL_HOSTNAME)  # type: ignore

# Quantos proxies reversos confiaveis existem na frente da aplicacao.
#
# X-Forwarded-For e escrito pelo cliente e so vira confiavel depois que um proxy
# nosso o reescreve. Com N proxies confiaveis, o IP real do visitante e a N-esima
# entrada contando da direita para a esquerda; tudo a esquerda disso e texto que o
# proprio cliente enviou e pode ser forjado.
#
# 0 (padrao) = acesso direto, ignora o cabecalho e usa REMOTE_ADDR.
# 1 = um proxy (nginx do compose, Render, Cloudflare).
# Aumente apenas se houver proxies confiaveis encadeados.
TRUSTED_PROXY_COUNT = config(
    "TRUSTED_PROXY_COUNT",
    default=1 if RENDER_EXTERNAL_HOSTNAME else 0,
    cast=int,
)

# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "rest_framework",
    # Guarda os refresh tokens invalidados no logout e na rotacao.
    "rest_framework_simplejwt.token_blacklist",
    "corsheaders",
    "accounts.apps.AccountsConfig",
    "shortener.apps.ShortenerConfig",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "whitenoise.middleware.WhiteNoiseMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "corsheaders.middleware.CorsMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "config.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "config.wsgi.application"


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

DATABASE_URL = os.environ.get("DATABASE_URL")

if DATABASE_URL:
    # producao render
    DATABASES = {
        "default": dj_database_url.config(
            default=DATABASE_URL,
            conn_max_age=600,
            conn_health_checks=True,
        )
    }
else:
    # desenvolvimento local
    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.postgresql",
            "NAME": config("DB_NAME", default="atalho_prancheta"),
            "USER": config("DB_USER", default="postgres"),
            "PASSWORD": config("DB_PASSWORD", default="postgres123"),
            "HOST": config("DB_HOST", default="db"),
            "PORT": config("DB_PORT", default="5432", cast=int),
        }
    }


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = "pt-br"

TIME_ZONE = "America/Sao_Paulo"

USE_I18N = True

USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = "/static/"
STATIC_ROOT = BASE_DIR / "staticfiles"

# WhiteNoise configuration
# Django >= 5.1 removeu STATICFILES_STORAGE; a configuracao agora vive em STORAGES.
STORAGES = {
    "default": {
        "BACKEND": "django.core.files.storage.FileSystemStorage",
    },
    "staticfiles": {
        "BACKEND": (
            "whitenoise.storage.CompressedManifestStaticFilesStorage"
            if not DEBUG
            else "whitenoise.storage.StaticFilesStorage"
        ),
    },
}

# Configurações adicionais do WhiteNoise
WHITENOISE_USE_FINDERS = True
WHITENOISE_AUTOREFRESH = DEBUG
WHITENOISE_ROOT = BASE_DIR / "staticfiles"

# Media files
MEDIA_URL = "/media/"
MEDIA_ROOT = BASE_DIR / "media"

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

# Cache

# `manage.py test` roda com o cache em memoria mesmo havendo Redis: teste que
# chama cache.clear() apagaria as contagens do ambiente inteiro, e a suite
# passa a exigir um servico no ar para rodar.
RUNNING_TESTS = sys.argv[1:2] == ["test"]

# O teto de criacao de link mora no cache. Com mais de um worker de gunicorn, um
# cache por processo daria a cada worker a sua propria contagem, e o limite
# efetivo seria o configurado vezes o numero de workers; reiniciar tambem zeraria
# tudo. O Redis mantem a conta num lugar so.
#
# Sem REDIS_URL a aplicacao continua de pe com o cache do processo — e o caso da
# venv local, que nao sobe o Compose.
REDIS_URL = config("REDIS_URL", default="")

if REDIS_URL and not RUNNING_TESTS:
    CACHES = {
        "default": {
            "BACKEND": "django.core.cache.backends.redis.RedisCache",
            "LOCATION": REDIS_URL,
        }
    }
else:
    CACHES = {
        "default": {
            "BACKEND": "django.core.cache.backends.locmem.LocMemCache",
        }
    }

# Cors Settings

# Lista explicita de quem pode chamar a API de outra origem. O valor vinha do
# .env desde sempre e era ignorado aqui — o allow-all antigo respondia a
# qualquer site.
CORS_ALLOWED_ORIGINS = config(
    "CORS_ALLOWED_ORIGINS",
    default="http://localhost:5173,http://127.0.0.1:5173",
    cast=Csv(),
)

# Escotilha para desenvolvimento com outra porta ou tunel. Fora disso, a lista
# acima e que vale.
CORS_ALLOW_ALL_ORIGINS = config("CORS_ALLOW_ALL_ORIGINS", default=False, cast=bool)

# A sessao e um JWT no cabecalho Authorization, que nao e "credencial" para o
# navegador — cookie nenhum precisa atravessar origem. Manter isto ligado junto
# do allow-all, como estava, e uma combinacao que o proprio padrao CORS proibe.
CORS_ALLOW_CREDENTIALS = False

# Rest Framework Settings

REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": [
        # Subclasse propria: mesma autenticacao, mensagens em portugues.
        "accounts.authentication.JWTAuthentication",
    ],
    # Sem permissao padrao: cada view declara a sua. O encurtador continua
    # aberto e as rotas de conta pedem autenticacao explicitamente.
    "DEFAULT_THROTTLE_RATES": {
        "auth-register": config("THROTTLE_REGISTER", default="20/hour"),
        "auth-login": config("THROTTLE_LOGIN", default="30/min"),
        "auth-refresh": config("THROTTLE_REFRESH", default="60/min"),
        # Criar link e a unica escrita aberta a quem nao tem conta.
        "link-create-anon": config("THROTTLE_LINK_ANON", default="20/hour"),
        "link-create-user": config("THROTTLE_LINK_USER", default="120/hour"),
    },
    "DEFAULT_PAGINATION_CLASS": "rest_framework.pagination.PageNumberPagination",
    "PAGE_SIZE": 10,
    "DEFAULT_RENDERER_CLASSES": [
        "rest_framework.renderers.JSONRenderer",
        # "rest_framework.renderers.BrowsableAPIRenderer",
    ],
    "DEFAULT_PARSER_CLASSES": [
        "rest_framework.parsers.JSONParser",
        "rest_framework.parsers.FormParser",
        "rest_framework.parsers.MultiPartParser",
    ],
}

# JSON Web Tokens

SIMPLE_JWT = {
    # Access curto porque um token assinado nao pode ser revogado antes de
    # expirar; o refresh e que carrega a sessao longa e esse da para invalidar.
    "ACCESS_TOKEN_LIFETIME": timedelta(minutes=config("JWT_ACCESS_MINUTES", default=30, cast=int)),
    "REFRESH_TOKEN_LIFETIME": timedelta(days=config("JWT_REFRESH_DAYS", default=7, cast=int)),
    # Cada refresh devolve um par novo e manda o anterior para a blacklist.
    "ROTATE_REFRESH_TOKENS": True,
    "BLACKLIST_AFTER_ROTATION": True,
    "UPDATE_LAST_LOGIN": True,
    "AUTH_HEADER_TYPES": ("Bearer",),
    "SIGNING_KEY": SECRET_KEY,
}

if not DEBUG:
    SECURE_SSL_REDIRECT = False
    SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    SECURE_BROWSER_XSS_FILTER = True
    SECURE_CONTENT_TYPE_NOSNIFF = True
    X_FRAME_OPTIONS = "DENY"
    SECURE_HSTS_SECONDS = 31536000
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True
