"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 4.2.7.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

import os
import sys
from datetime import timedelta
from pathlib import Path

import dj_database_url
from decouple import Csv, config

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Core settings

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = config("SECRET_KEY", default="django-insecure-dev-key-change-in-production")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = config("DEBUG", default=True, cast=bool)

ALLOWED_HOSTS = config(
    "ALLOWED_HOSTS",
    default="localhost,127.0.0.1",
    cast=lambda v: [s.strip() for s in v.split(",")],
)

INTERNAL_ALLOWED_HOSTS = config("INTERNAL_ALLOWED_HOSTS", default="", cast=Csv())
for internal_host in INTERNAL_ALLOWED_HOSTS:
    if internal_host and internal_host not in ALLOWED_HOSTS:
        ALLOWED_HOSTS.append(internal_host)

# Link curto por subdominio: `loja-natal.atalho.app`.
#
# Este e o dominio sob o qual os subdominios de link respondem. Vazio (o padrao)
# desliga a funcionalidade por inteiro: o middleware nao olha o Host e o painel
# nao oferece o campo. E o que mantem a suite e a venv local rodando sem
# configuracao nenhuma.
#
# Ligar isto em producao exige tres coisas do lado de fora, descritas no
# DEPLOY.md: um registro DNS curinga, um certificado curinga e o `server_name`
# do nginx aceitando o curinga.
SHORTLINK_BASE_DOMAIN = config("SHORTLINK_BASE_DOMAIN", default="").strip().lower().lstrip(".")

if SHORTLINK_BASE_DOMAIN:
    # O ponto na frente e a sintaxe do Django para "este dominio e qualquer
    # subdominio dele". Sem isto, todo acesso por subdominio morreria em
    # DisallowedHost antes de chegar ao middleware.
    # Sem a porta: o Django a separa do Host antes de conferir esta lista, e
    # uma entrada com porta nunca casaria com nada. Em desenvolvimento o valor
    # costuma ser `localhost:8000`, por causa do endereco montado para a tela.
    wildcard_host = f".{SHORTLINK_BASE_DOMAIN.split(':')[0]}"
    if wildcard_host not in ALLOWED_HOSTS:
        ALLOWED_HOSTS.append(wildcard_host)

# 302 ou 307. Os dois sao temporarios — o que este servico nunca devolve e 301,
# que o navegador guarda para sempre e deixaria o dono sem poder trocar o
# destino de um link ja clicado. A diferenca entre os dois e o metodo: o 307
# obriga a repetir a requisicao como veio; num link divulgado, sempre GET, da no
# mesmo.
SHORTLINK_REDIRECT_STATUS = config("SHORTLINK_REDIRECT_STATUS", default=302, cast=int)

if SHORTLINK_REDIRECT_STATUS not in (302, 307):
    raise ValueError("SHORTLINK_REDIRECT_STATUS aceita 302 ou 307.")

# Quantos proxies reversos confiaveis existem na frente da aplicacao.
#
# X-Forwarded-For e escrito pelo cliente e so vira confiavel depois que um proxy
# nosso o reescreve. Com N proxies confiaveis, o IP real do visitante e a N-esima
# entrada contando da direita para a esquerda; tudo a esquerda disso e texto que o
# proprio cliente enviou e pode ser forjado.
#
# 0 (padrao) = acesso direto, ignora o cabecalho e usa REMOTE_ADDR.
# 1 = um proxy: e o caso da VPS, onde o nginx esta na frente do gunicorn.
# 2 = dois, por exemplo com a Cloudflare na frente desse nginx.
# Aumente apenas com proxies confiaveis encadeados — cada unidade a mais confia
# em uma entrada que o cliente pode ter forjado.
TRUSTED_PROXY_COUNT = config("TRUSTED_PROXY_COUNT", default=0, cast=int)

# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "rest_framework",
    # Guarda os refresh tokens invalidados no logout e na rotacao.
    "rest_framework_simplejwt.token_blacklist",
    "corsheaders",
    "accounts.apps.AccountsConfig",
    "shortener.apps.ShortenerConfig",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    # Antes de tudo que serve conteudo: num acesso por subdominio o caminho e
    # `/`, o mesmo da pagina inicial, e o subdominio pertence ao link inteiro.
    "shortener.middleware.SubdomainRedirectMiddleware",
    "whitenoise.middleware.WhiteNoiseMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "corsheaders.middleware.CorsMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "config.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "config.wsgi.application"


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

DATABASE_URL = os.environ.get("DATABASE_URL")

if DATABASE_URL:
    # DATABASE_URL num so campo, no formato postgres://usuario:senha@host:porta/base
    DATABASES = {
        "default": dj_database_url.config(
            default=DATABASE_URL,
            conn_max_age=600,
            conn_health_checks=True,
        )
    }
else:
    # desenvolvimento local
    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.postgresql",
            "NAME": config("DB_NAME", default="atalho_prancheta"),
            "USER": config("DB_USER", default="postgres"),
            "PASSWORD": config("DB_PASSWORD", default="postgres123"),
            "HOST": config("DB_HOST", default="db"),
            "PORT": config("DB_PORT", default="5432", cast=int),
        }
    }


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = "pt-br"

TIME_ZONE = "America/Sao_Paulo"

USE_I18N = True

USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = "/static/"
STATIC_ROOT = BASE_DIR / "staticfiles"

# WhiteNoise configuration
# Django >= 5.1 removeu STATICFILES_STORAGE; a configuracao agora vive em STORAGES.
STORAGES = {
    "default": {
        "BACKEND": "django.core.files.storage.FileSystemStorage",
    },
    "staticfiles": {
        "BACKEND": (
            "whitenoise.storage.CompressedManifestStaticFilesStorage"
            if not DEBUG
            else "whitenoise.storage.StaticFilesStorage"
        ),
    },
}

# Configurações adicionais do WhiteNoise
WHITENOISE_USE_FINDERS = True
WHITENOISE_AUTOREFRESH = DEBUG
WHITENOISE_ROOT = BASE_DIR / "staticfiles"

# Media files
MEDIA_URL = "/media/"
MEDIA_ROOT = BASE_DIR / "media"

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

# Origens em que o Django confia para o CSRF (o formulario de login do admin,
# por exemplo). Atras de um proxy TLS a comparacao e feita contra esta lista, e
# sem o dominio aqui o login responde 403 mesmo com a senha certa.
CSRF_TRUSTED_ORIGINS = config("CSRF_TRUSTED_ORIGINS", default="", cast=Csv())

# Cache

# `manage.py test` roda com o cache em memoria mesmo havendo Redis: teste que
# chama cache.clear() apagaria as contagens do ambiente inteiro, e a suite
# passa a exigir um servico no ar para rodar.
RUNNING_TESTS = sys.argv[1:2] == ["test"]

# O teto de criacao de link mora no cache. Com mais de um worker de gunicorn, um
# cache por processo daria a cada worker a sua propria contagem, e o limite
# efetivo seria o configurado vezes o numero de workers; reiniciar tambem zeraria
# tudo. O Redis mantem a conta num lugar so.
#
# Sem REDIS_URL a aplicacao continua de pe com o cache do processo — e o caso da
# venv local, que nao sobe o Compose.
REDIS_URL = config("REDIS_URL", default="")

if REDIS_URL and not RUNNING_TESTS:
    CACHES = {
        "default": {
            "BACKEND": "django.core.cache.backends.redis.RedisCache",
            "LOCATION": REDIS_URL,
        }
    }
else:
    CACHES = {
        "default": {
            "BACKEND": "django.core.cache.backends.locmem.LocMemCache",
        }
    }

# Cors Settings

# Lista explicita de quem pode chamar a API de outra origem. O valor vinha do
# .env desde sempre e era ignorado aqui — o allow-all antigo respondia a
# qualquer site.
CORS_ALLOWED_ORIGINS = config(
    "CORS_ALLOWED_ORIGINS",
    default="http://localhost:5173,http://127.0.0.1:5173",
    cast=Csv(),
)

# Escotilha para desenvolvimento com outra porta ou tunel. Fora disso, a lista
# acima e que vale.
CORS_ALLOW_ALL_ORIGINS = config("CORS_ALLOW_ALL_ORIGINS", default=False, cast=bool)

# A sessao e um JWT no cabecalho Authorization, que nao e "credencial" para o
# navegador — cookie nenhum precisa atravessar origem. Manter isto ligado junto
# do allow-all, como estava, e uma combinacao que o proprio padrao CORS proibe.
CORS_ALLOW_CREDENTIALS = False

# Rest Framework Settings

REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": [
        # Subclasse propria: mesma autenticacao, mensagens em portugues.
        "accounts.authentication.JWTAuthentication",
    ],
    # Sem permissao padrao: cada view declara a sua. O encurtador continua
    # aberto e as rotas de conta pedem autenticacao explicitamente.
    "DEFAULT_THROTTLE_RATES": {
        "auth-register": config("THROTTLE_REGISTER", default="20/hour"),
        "auth-login": config("THROTTLE_LOGIN", default="30/min"),
        "auth-refresh": config("THROTTLE_REFRESH", default="60/min"),
        # Criar link e a unica escrita aberta a quem nao tem conta.
        "link-create-anon": config("THROTTLE_LINK_ANON", default="20/hour"),
        "link-create-user": config("THROTTLE_LINK_USER", default="120/hour"),
        # Pedir o link manda e-mail para um endereco que quem pede digitou: e
        # por aqui que alguem lotaria a caixa de entrada de outra pessoa.
        "auth-password-reset": config("THROTTLE_PASSWORD_RESET", default="5/hour"),
        "auth-password-confirm": config("THROTTLE_PASSWORD_CONFIRM", default="30/hour"),
    },
    "DEFAULT_PAGINATION_CLASS": "rest_framework.pagination.PageNumberPagination",
    "PAGE_SIZE": 10,
    "DEFAULT_RENDERER_CLASSES": [
        "rest_framework.renderers.JSONRenderer",
        # "rest_framework.renderers.BrowsableAPIRenderer",
    ],
    "DEFAULT_PARSER_CLASSES": [
        "rest_framework.parsers.JSONParser",
        "rest_framework.parsers.FormParser",
        "rest_framework.parsers.MultiPartParser",
    ],
}

# JSON Web Tokens

SIMPLE_JWT = {
    # Access curto porque um token assinado nao pode ser revogado antes de
    # expirar; o refresh e que carrega a sessao longa e esse da para invalidar.
    "ACCESS_TOKEN_LIFETIME": timedelta(minutes=config("JWT_ACCESS_MINUTES", default=30, cast=int)),
    "REFRESH_TOKEN_LIFETIME": timedelta(days=config("JWT_REFRESH_DAYS", default=7, cast=int)),
    # Cada refresh devolve um par novo e manda o anterior para a blacklist.
    "ROTATE_REFRESH_TOKENS": True,
    "BLACKLIST_AFTER_ROTATION": True,
    "UPDATE_LAST_LOGIN": True,
    "AUTH_HEADER_TYPES": ("Bearer",),
    "SIGNING_KEY": SECRET_KEY,
}

# Redefinicao de senha

# O endereco da interface, para montar o link que vai no e-mail.
#
# Declarado, e nunca tirado do Host da requisicao: o Host e escrito por quem
# pede, e um link montado a partir dele mandaria o token de outra pessoa para o
# endereco que o atacante quisesse. Com o link por subdominio ligado isso nem
# exige dominio proprio — `qualquer.seudominio.com.br` passa no ALLOWED_HOSTS.
#
# Em producao sai do DOMAIN que o nginx ja usa; em desenvolvimento, do Vite.
DOMAIN = config("DOMAIN", default="").strip().lower()
SITE_URL = config(
    "SITE_URL",
    default=f"https://{DOMAIN}" if DOMAIN else "http://localhost:5173",
).rstrip("/")

# Quanto tempo o link vale. O padrao do Django e de tres dias, longo demais
# para um link que abre a conta inteira a quem tiver o e-mail na mao.
PASSWORD_RESET_TIMEOUT = config("PASSWORD_RESET_MINUTES", default=60, cast=int) * 60

# O e-mail sai fora da requisicao, numa thread: SMTP leva segundos, e uma
# resposta mais lenta so quando a conta existe contaria a quem pergunta quais
# e-mails tem conta aqui. Nos testes sai na hora, para a caixa de saida do
# Django ja estar preenchida quando a assercao olhar.
PASSWORD_RESET_EMAIL_IN_BACKGROUND = not RUNNING_TESTS

# E-mail

# Sem EMAIL_HOST, a mensagem e impressa no log do backend em vez de enviada — e
# o que permite testar a redefinicao em desenvolvimento sem servidor nenhum, e o
# que deixa a producao de pe enquanto o SMTP nao estiver configurado.
EMAIL_HOST = config("EMAIL_HOST", default="")
EMAIL_BACKEND = config(
    "EMAIL_BACKEND",
    default=(
        "django.core.mail.backends.smtp.EmailBackend"
        if EMAIL_HOST
        else "django.core.mail.backends.console.EmailBackend"
    ),
)
EMAIL_PORT = config("EMAIL_PORT", default=587, cast=int)
EMAIL_HOST_USER = config("EMAIL_HOST_USER", default="")
EMAIL_HOST_PASSWORD = config("EMAIL_HOST_PASSWORD", default="")
# 587 fala STARTTLS; 465 fala TLS desde o primeiro byte. Um ou outro, nunca os
# dois — o Django recusa o envio com os dois ligados. Por isso o padrao de um e o
# contrario do outro: quem so declara EMAIL_USE_SSL=True nao tropeca no TLS.
EMAIL_USE_SSL = config("EMAIL_USE_SSL", default=False, cast=bool)
EMAIL_USE_TLS = config("EMAIL_USE_TLS", default=not EMAIL_USE_SSL, cast=bool)
EMAIL_TIMEOUT = 15
DEFAULT_FROM_EMAIL = config(
    "DEFAULT_FROM_EMAIL",
    default=f"Atalho Prancheta <nao-responda@{DOMAIN or 'localhost'}>",
)

if not DEBUG:
    # O desvio de http para https e feito pelo nginx, antes da requisicao chegar
    # ao gunicorn. Ligue apenas se um dia o Django ficar exposto sem proxy.
    SECURE_SSL_REDIRECT = config("SECURE_SSL_REDIRECT", default=False, cast=bool)
    SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    SECURE_BROWSER_XSS_FILTER = True
    SECURE_CONTENT_TYPE_NOSNIFF = True
    X_FRAME_OPTIONS = "DENY"
    SECURE_HSTS_SECONDS = 31536000
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True
