# Generated by Django 6.0.8 on 2026-08-21 18:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shortener", "0002_alter_click_url"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="shortenedurl",
            name="owner",
            field=models.ForeignKey(
                blank=True,
                help_text="Conta que criou o link. Vazio para link criado sem conta",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="links",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Dono",
            ),
        ),
        migrations.AddIndex(
            model_name="shortenedurl",
            index=models.Index(
                fields=["owner", "-created_at"], name="shortener_s_owner_i_0c6370_idx"
            ),
        ),
    ]
