# Generated by Django 6.0.8 on 2026-08-23 19:56

from django.conf import settings
from django.db import migrations, models

import shortener.slugs


class Migration(migrations.Migration):

    dependencies = [
        ("shortener", "0003_shortenedurl_owner_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="shortenedurl",
            name="subdomain",
            field=models.CharField(
                blank=True,
                db_index=True,
                help_text="Rotulo que responde em {subdominio}.{dominio}. Vazio para link so no caminho",
                max_length=32,
                null=True,
                unique=True,
                validators=[shortener.slugs.validate_slug],
                verbose_name="Subdominio",
            ),
        ),
        migrations.AlterField(
            model_name="shortenedurl",
            name="short_code",
            field=models.CharField(
                db_index=True,
                help_text="Codigo unico para a URL encurtada",
                max_length=32,
                unique=True,
                validators=[shortener.slugs.validate_slug],
                verbose_name="Codigo Curto",
            ),
        ),
        migrations.AddIndex(
            model_name="shortenedurl",
            index=models.Index(fields=["subdomain"], name="shortener_s_subdoma_6dbe6b_idx"),
        ),
    ]
